### ISSUE TITLE
all switch items show up as lamps?

### ISSUE THREAD

**Issue by snizzleorg** [htreu/OpenHAB-HomeKit-Bridge#29]
all switch items show up as lamps in homekit. is there any way to tell homekit bridge what type of device an item is?

**Comment by htreu** [comment]
not yet. please see this issue and comment: https://github.com/htreu/OpenHAB-HomeKit-Bridge/issues/21#issuecomment-149919940

this will be one of the next features.

**Comment by snizzleorg** [comment]
ok. thanks

**Comment by turley** [comment]
There's no clear way (that I know) to determine from openHAB whether a switch is a *light* switch or another kind of switch.

With other devices, the openHAB element type alone may be enough to determine the appropriate HomeKit accessory, and if there's still ambiguity, the underlying item can usually give us enough information. Rollershutters (which are normally exposed as openHAB Switch elements) can be determined using the item type, but for lights and outlet switches, there's often no real distinction in openHAB.

One option would be to look at the sitemap element's "icon" attribute. Luckily, the REST API exposes the icon with each sitemap element, whether it's actually defined at the item level or the sitemap level.

Unfortunately, I believe the icons are UI-specific (and can be custom), so I don't think there's any "standard" set or anything. That being said, if the bridge is functionally similar to a UI (even if just for the sake of bridging two different systems), it might make sense to pick a sensible mapping of "icons" to accessory types for switches.

The classic openHAB UI's default "switch" icon (which becomes "switch-on.png" or "switch-off.png" because it looks for \<icon\>-\<state\>.png before \<icon\>.png) is styled as a lightbulb, so perhaps OpenHAB-HomeKit-Bridge could use the Lightbulb HomeKit accessory in that case, and a generic Switch accessory for any other icon. I suppose other icons could take on special meaning as more accessories are implemented.

Anyway, that's just one possibility, and it's obviously not the most elegant solution in the world. As htreu mentioned, some kind of special naming convention could work as well.

I'm afraid it may have to be a little bit kludgy either way.
