### ISSUE TITLE
Not possible to set temperature

### ISSUE THREAD

**Issue by milymat** [htreu/OpenHAB-HomeKit-Bridge#32]
Hi,

I used a Slider in my Sitemap to change the tempature, but it's not working. The temperature is shown as Text.

Any Idea?

**Comment by htreu** [comment]
The temperature item can be used with Number items which return float values, like temperature sensors: ```Number Temp_Outside "Outside [%.1f °C]"  <temperature> (Weather) { onewire="deviceId=xxxx;propertyName=temperature" }```
The homekit sitemap should export them as Text items: ```Text item=Temp_Outside label="Outside"```. 
The unit is always _Celsius_.

**Comment by marconett** [comment]
this doesn't really explain how to configure the the homekit bridge to be able to set a temperature. is it possible?

**Comment by htreu** [comment]
Actually you are right. Its not possible right now. The TextItems taken from the sitemap are read only at the moment. Are you trying to control a thermostat?

**Comment by marconett** [comment]
Yes I am. I have been looking into this today but my biggest hurdle is that I would need to translate multiple openHAB sitemap elements (currentTemperature, targetTemperature, currentHumidity; i.e. switch, text, setpoint) into a single homekit accessory.

right now i'm trying to understand your code to try and add something that would make this possible (probably using a group element in openHAB), but I'm not super familiar with nodeJS.

**Comment by marconett** [comment]
I started creating a Thermostat subtype, but I don't yet fully understand how the AccessoryProvider and the element factory work.

https://github.com/marconett/OpenHAB-HomeKit-Bridge/blob/c7a3f810f9be03a9e11edbabae840cf818d5a918/lib/subtypes/ThermostatItem.js

Do you mind opening this issue again?

**Comment by htreu** [comment]
Not at all. This plays into the same direction as #29.

**Comment by htreu** [comment]
your thermostat subtype looks okay for the first draft. the interfacing to openhab now needs to connect to the different urls of the groups items. another thing will be to recognise/detect the given group as a thermostat. This may be done using special strings or by analysing the grouped item types.

**Comment by marconett** [comment]
see my commits here: https://github.com/marconett/OpenHAB-HomeKit-Bridge/commits/master

to properly implement group support (evaluation of all elements inside of every group), i would need to change something more fundamental. the way it currently works, only a single openhab element can be a single accessory.

The elements inside a group are just elements from ElementType.js. but because of the way those are instantiated right now (openHABBridge.js -> AccessoryProvider.js -> ElementType.js -> element), I can't just let my group element instantiated, for example, two unique SwitchItems. The AccessoryProvider.js would need to do that. I'm not quite sure how to solve this in the most elegant way.

So for now, i'm sticking with the "if there's a group, then it's a thermostat"-approach.

still got to solve problems with the update listener, as it's no use to put an it onto a group.

**Comment by marconett** [comment]
Sorry, I already gave up in this.. I implemented my own: https://github.com/marconett/openHAB-433-HomeKit-Bridge

I'm Not working on this anymore. You might want to close the issue again.

**Comment by htreu** [comment]
I will simplement the basics in the next weeks and will ping you for input then. good luck with the go implementation!

**Comment by marconett** [comment]
sure, i'll test it with my thermostat if wou want
